# Generated by Django 3.2 on 2021-04-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, choices=[('strong', 'Strong'), ('medium', 'Medium'), ('unsafe', 'Unsafe'), ('obvius', 'Obvious')], max_length=15, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('last_accessed', models.DateTimeField(auto_now=True, verbose_name='acessado em')),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
