# Generated by Django 3.2 on 2021-04-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210408_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='credential',
            name='link',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='credential',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='credential',
            name='status',
            field=models.CharField(blank=True, choices=[('strong', 'Strong'), ('medium', 'Medium'), ('unsafe', 'Unsafe'), ('obvius', 'Obvious')], default='obvius', max_length=15),
        ),
    ]
