# Generated by Django 3.2 on 2021-05-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_passcoord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passimage_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.DeleteModel(
            name='PassImage',
        ),
    ]
