# Generated by Django 3.2 on 2021-05-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_credential_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.credential'),
        ),
    ]
