# Generated by Django 3.2 on 2021-06-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210531_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.BinaryField(),
        ),
    ]
