export default {
    CREDENTIAL_CREATION: 'CREDENTIAL_CREATION',
    PASSWORD_ACCESS: 'PASSWORD_ACCESS',
    CREDENTIAL_EDITING: 'CREDENTIAL_EDITING',
    ACCOUNT_LOGIN: 'ACCOUNT_LOGIN',
    ACCOUNT_LOGOUT: 'ACCOUNT_LOGOUT',
    CREDENTIAL_DELETE: 'CREDENTIAL_DELETE',
    CREDENTIAL_COPY: 'CREDENTIAL_COPY',
    ACCOUNT_ACCESS: 'ACCOUNT_ACCESS'
}